### PR TITLE
New release v1.7.1 from upstream.

### PR DESCRIPTION
**Pull request by vitenti**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by vitenti** [comment]
@conda-forge-admin, please rerender

**Comment by vitenti** [comment]
@conda-forge-admin, please rerender

**Review by beckermr — CHANGES_REQUESTED** [review]
The new maintainer needs comment on this PR that they are ok being on the feedstock before it can be merged.

Also, conda-forge's bots will generate this PR for you if you wait long enough.

**Comment by mattkwiecien** [comment]
@beckermr I am ok with being added as a maintainer!  Thanks.

**Pull request merged**
